/**
 * Lockfile parsing and diff helpers.
 *
 * Frontend projects hop between npm/yarn/pnpm/bun and each one has its
 * own lockfile format. toolchain-rs tries to be the single binary that
 * understands all four — this module is the normalised view the
 * resolver queries ("what version of react is locked?") and the diff
 * machinery powering the CLI's `toolchain diff` command.
 */

export type LockfileFormat = "npm" | "yarn-classic" | "yarn-berry" | "pnpm" | "bun";

export type LockedPackage = {
  name: string;
  version: string;
  /** Whose direct dependency brought this in. "" = top-level. */
  broughtInBy: string;
  integrity?: string;
  resolved?: string;
  dependencies?: Record<string, string>;
};

export type NormalisedLockfile = {
  format: LockfileFormat;
  lockfileVersion: number;
  packages: LockedPackage[];
};

/**
 * Detect which lockfile format a raw string is in. Cheap, content-based;
 * filename hints may be unreliable when lockfiles are piped in.
 */
export function detectFormat(raw: string): LockfileFormat | null {
  if (/^\s*#\s*This file is generated by run of bun/m.test(raw)) return "bun";
  if (/^\s*lockfileVersion:\s*'?6|^\s*lockfileVersion:\s*'?9/m.test(raw)) return "pnpm";
  if (/^\s*lockfileVersion:\s*'?5/m.test(raw)) return "pnpm";
  if (/^\s*__metadata:\s*$/m.test(raw)) return "yarn-berry";
  if (/^# yarn lockfile v1$/m.test(raw)) return "yarn-classic";
  try {
    const parsed = JSON.parse(raw);
    if (parsed && typeof parsed === "object" && "lockfileVersion" in parsed) {
      return "npm";
    }
  } catch {
    /* not JSON */
  }
  return null;
}

/**
 * Parse an npm v7+ `package-lock.json` into the normalised shape.
 * Other formats get their own parsers; keeping this one in-module
 * as the reference implementation.
 */
export function parseNpmLock(raw: string): NormalisedLockfile {
  const doc = JSON.parse(raw) as {
    lockfileVersion: number;
    packages?: Record<string, {
      version?: string;
      resolved?: string;
      integrity?: string;
      dependencies?: Record<string, string>;
      dev?: boolean;
    }>;
  };
  const packages: LockedPackage[] = [];
  for (const [path, info] of Object.entries(doc.packages ?? {})) {
    if (path === "") continue;
    const name = path.startsWith("node_modules/")
      ? path.slice("node_modules/".length).replace(/.*\/node_modules\//, "")
      : path;
    packages.push({
      name,
      version: info.version ?? "",
      broughtInBy: path,
      integrity: info.integrity,
      resolved: info.resolved,
      dependencies: info.dependencies,
    });
  }
  return {
    format: "npm",
    lockfileVersion: doc.lockfileVersion ?? 0,
    packages,
  };
}

export type LockDiff = {
  added: { name: string; version: string }[];
  removed: { name: string; version: string }[];
  upgraded: { name: string; from: string; to: string }[];
  downgraded: { name: string; from: string; to: string }[];
};

export function diff(a: NormalisedLockfile, b: NormalisedLockfile): LockDiff {
  const aMap = new Map<string, string>();
  const bMap = new Map<string, string>();
  for (const p of a.packages) aMap.set(p.name, p.version);
  for (const p of b.packages) bMap.set(p.name, p.version);

  const added: LockDiff["added"] = [];
  const removed: LockDiff["removed"] = [];
  const upgraded: LockDiff["upgraded"] = [];
  const downgraded: LockDiff["downgraded"] = [];

  for (const [name, version] of bMap) {
    const prev = aMap.get(name);
    if (prev === undefined) {
      added.push({ name, version });
      continue;
    }
    if (prev === version) continue;
    const cmp = semverCompare(prev, version);
    if (cmp < 0) upgraded.push({ name, from: prev, to: version });
    else if (cmp > 0) downgraded.push({ name, from: prev, to: version });
  }
  for (const [name, version] of aMap) {
    if (!bMap.has(name)) removed.push({ name, version });
  }
  return { added, removed, upgraded, downgraded };
}

/**
 * Minimal semver-ish comparator: enough to say which side is newer for
 * the diff output. Not a full semver implementation — pre-release
 * handling is coarse.
 */
export function semverCompare(a: string, b: string): number {
  const [aMain, aPre] = a.split("-", 2);
  const [bMain, bPre] = b.split("-", 2);
  const as = aMain.split(".").map((x) => parseInt(x, 10) || 0);
  const bs = bMain.split(".").map((x) => parseInt(x, 10) || 0);
  while (as.length < 3) as.push(0);
  while (bs.length < 3) bs.push(0);
  for (let i = 0; i < 3; i++) {
    if (as[i] !== bs[i]) return as[i] < bs[i] ? -1 : 1;
  }
  if (aPre && !bPre) return -1;
  if (!aPre && bPre) return 1;
  if (aPre && bPre) return aPre.localeCompare(bPre);
  return 0;
}
